language: python
python:
  - "3.6"
cache: pip
install:
  - pip install numpy beautifulsoup4 Pygments CommonMark
script:
  - python -m pytest -s tests/test_snowy.py
  - python -m pytest -s tests/test_io.py
  - python -m pytest -s tests/test_dist.py
  - python -m pytest -s docs/generate.py
