language: python
python:
  - "3.6"
cache: pip
install:
  - pip install numpy imageio numba
script:
  - python -m pytest -s tests/test_snowy.py
  - python -m pytest -s tests/test_io.py
  - python -m pytest -s tests/test_dist.py

  - pip install beautifulsoup4 Pygments CommonMark scipy
  - python docs/generate.py

  - python3 setup.py sdist bdist_wheel
